Feature/species choice screen
PetJournal/petjournal.android pull request #28
Opened 2023-09-05 00:59 UTC by LucasOliveiraSimao

desenvolvido a tela de escolha de pets conforme o modelo do figma

2023-09-05 12:01 UTC, gusoliveira21 requested changes

2023-09-16 23:20 UTC, LucasOliveiraSimao commented on petJournal/app/src/main/java/com/soujunior/petjournal/ui/appArea/speciesChoiceScreen/components/Screen.kt
> +    Scaffold(
Eu retirei, eu não sabia que poderia gerar algum bug

2023-09-16 23:20 UTC, LucasOliveiraSimao commented on petJournal/app/src/main/java/com/soujunior/petjournal/ui/appArea/speciesChoiceScreen/components/Screen.kt
> +@SuppressLint("UnusedMaterial3ScaffoldPaddingParameter")
Foi removido

2023-09-16 23:22 UTC, LucasOliveiraSimao commented on petJournal/app/src/main/java/com/soujunior/petjournal/ui/appArea/speciesChoiceScreen/components/GridVectors.kt
> +//// Gustavo isso aqui talvez possa ir pra UTILS e ser reutilizado dps de alguns ajustes.
Esse comentario ja esta quando eu copie o trecho de código

2023-09-27 18:32 UTC, merged