Feature/birth pet screen
PetJournal/petjournal.android pull request #57
Opened 2024-04-07 15:51 UTC by JorgeTranin

2024-04-09 12:48 UTC, gusoliveira21 commented
@JorgeTranin Tente rodar sua aplicação em dispositivos diferentes no emulador:
Android 8.1 ("Oreo") | x86 API 27 apresentou erro.
FATAL EXCEPTION: main
Process: com.soujunior.petjournal, PID: 11495
java.lang.RuntimeException: Canvas: trying to draw too large(441000000bytes) bitmap.
	at android.view.DisplayListCanvas.throwIfCannotDraw(DisplayListCanvas.java:229)
	at android.view.RecordingCanvas.drawBitmap(RecordingCanvas.java:97)
	at androidx.compose.ui.graphics.AndroidCanvas.drawImageRect-HPBpro0(AndroidCanvas.android.kt:271)
	at androidx.compose.ui.graphics.drawscope.CanvasDrawScope.drawImage-AZ2fEMs(CanvasDrawScope.kt:263)
	at androidx.compose.ui.node.LayoutNodeDrawScope.drawImage-AZ2fEMs(Unknown Source:39)
	at androidx.compose.ui.graphics.drawscope.DrawScope.drawImage-AZ2fEMs$default(DrawScope.kt:510)
	at androidx.compose.ui.graphics.painter.BitmapPainter.onDraw(BitmapPainter.kt:93)
	at androidx.compose.ui.graphics.painter.Painter.draw-x_KDEd0(Painter.kt:212)
	at androidx.compose.ui.draw.PainterModifierNode.draw(PainterModifier.kt:347)
	at androidx.compose.ui.node.LayoutNodeDrawScope.draw-x_KDEd0$ui_release(LayoutNodeDrawScope.kt:92)
	at androidx.compose.ui.node.NodeCoordinator.drawContainedDrawModifiers(NodeCoordinator.kt:370)
	at androidx.compose.ui.node.NodeCoordinator.draw(NodeCoordinator.kt:359)
	at androidx.compose.ui.node.LayoutModifierNodeCoordinator.performDraw(LayoutModifierNodeCoordinator.kt:236)
	at androidx.compose.ui.node.NodeCoordinator.drawContainedDrawModifiers(NodeCoordinator.kt:367)
	at androidx.compose.ui.node.NodeCoordinator.access$drawContainedDrawModifiers(NodeCoordinator.kt:58)
	at androidx.compose.ui.node.NodeCoordinator$invoke$1.invoke(NodeCoordinator.kt:396)
	at androidx.compose.ui.node.NodeCoordinator$invoke$1.invoke(NodeCoordinator.kt:395)
	at androidx.compose.runtime.snapshots.Snapshot$Companion.observe(Snapshot.kt:2200)
	at androidx.compose.runtime.snapshots.SnapshotStateObserver$observeReads$1$1.invoke(SnapshotStateObserver.kt:234)
	at androidx.compose.runtime.snapshots.SnapshotStateObserver$observeReads$1$1.invoke(SnapshotStateObserver.kt:230)
	at androidx.compose.runtime.SnapshotStateKt__DerivedStateKt.observeDerivedStateRecalculations(DerivedState.kt:341)
	at androidx.compose.runtime.SnapshotStateKt.observeDerivedStateRecalculations(Unknown Source:1)
	at androidx.compose.runtime.snapshots.SnapshotStateObserver.observeReads(SnapshotStateObserver.kt:230)
	at androidx.compose.ui.node.OwnerSnapshotObserver.observeReads$ui_release(OwnerSnapshotObserver.kt:120)
	at androidx.compose.ui.node.NodeCoordinator.invoke(NodeCoordinator.kt:395)
	at androidx.compose.ui.node.NodeCoordinator.invoke(NodeCoordinator.kt:58)
	at androidx.compose.ui.platform.RenderNodeApi23.record(RenderNodeApi23.android.kt:280)
	at androidx.compose.ui.platform.RenderNodeLayer.updateDisplayList(RenderNodeLayer.android.kt:301)
	at androidx.compose.ui.platform.RenderNodeLayer.drawLayer(RenderNodeLayer.android.kt:242)
	at androidx.compose.ui.node.NodeCoordinator.draw(NodeCoordinator.kt:354)
	at androidx.compose.ui.node.LayoutModifierNodeCoordinator.performDraw(LayoutModifierNodeCoordinator.kt:236)
	at androidx.compose.ui.node.LayoutNodeDrawScope.drawContent(LayoutNodeDrawScope.kt:64)
	at androidx.compose.foundation.Background.draw(Background.kt:107)
	at androidx.compose.ui.node.BackwardsCompatNode.draw(BackwardsCompatNode.kt:361)
	at androidx.compose.ui.node.LayoutNodeDrawScope.draw-x_KDEd0$ui_release(LayoutNodeDrawScope.kt:92)
	at androidx.compose.ui.node.NodeCoordinator.drawContainedDrawModifiers(NodeCoordinator.kt:370)
	at androidx.compose.ui.node.NodeCoordinator.draw(NodeCoordinator.kt:359)
	at androidx.compose.ui.node.LayoutModifierNodeCoordinator.performDraw(LayoutModifierNodeCoordinator.kt:236)
	at androidx.compose.ui.node.NodeCoordinator.drawContainedDrawModifiers(NodeCoordinator.kt:367)
	at androidx.compose.ui.node.NodeCoordinator.draw(NodeCoordinator.kt:359)
	at androidx.compose.ui.node.LayoutNode.draw$ui_release(LayoutNode.kt:866)

2024-04-09 14:15 UTC, gusoliveira21 commented on petJournal/app/src/main/java/com/soujunior/petjournal/ui/navigation/MainActivity.kt
> -            PresentationManager()
???

2024-04-09 14:17 UTC, gusoliveira21 commented on petJournal/app/src/main/java/com/soujunior/petjournal/ui/navigation/NavHostElements.kt
>  fun NavTestScreen(){
Ainda é necessário manter o NavTestScreen() ? se não, pode remover

2024-04-09 14:17 UTC, gusoliveira21 requested changes
Remova métodos não utilizados como "success()".
Remova comentários (se o método ou classe não tiver em seu nome o objetivo claro do que ela faz, refatore para que ela faça isso).

2024-04-09 14:25 UTC, gusoliveira21 commented on petJournal/app/src/main/java/com/soujunior/petjournal/ui/appArea/pets/petNameAndGenderScreen/ViewModelNameGenderImpl.kt
> +           // result.handleResult(::success, ::failed)
remover se não estiver sendo usado

2024-04-09 14:26 UTC, gusoliveira21 commented on petJournal/data/src/main/java/com/soujunior/data/repository/GuardianRepositoryImpl.kt
> +            Log.i("tt", e.message.toString())
TAG

2024-04-09 14:27 UTC, gusoliveira21 commented on petJournal/app/src/main/java/com/soujunior/petjournal/ui/appArea/pets/petNameAndGenderScreen/ViewModelNameGenderImpl.kt
> +        //getPetInformation(state.idPetInformation!!)
?

2024-04-09 14:27 UTC, gusoliveira21 commented on petJournal/app/src/main/java/com/soujunior/petjournal/ui/appArea/pets/petNameAndGenderScreen/ViewModelNameGenderImpl.kt
> -        getPetInformation(1)
?

2024-04-09 14:31 UTC, gusoliveira21 commented
@JorgeTranin Refatora o código de modo a remover os comentários, códigos não utilizados e logs que não usem TAG, ou só adiciona TAG nelas. Tente remover também alguns métodos criados para testes como NavTestScreen() , generic(), ...

2024-04-15 16:53 UTC, N0stalgiaUltra requested changes
Screen.kt 
linhas 76, 83, 84, adicionar strings ao Strings Resources (strings.xml)

obs: não precisava remover o navhost de teste de telas. Eu deixava ele só pra n ter que alterar o metodo original, mas tb n tem problema ele ter sido removido.

2024-04-15 19:04 UTC, JorgeTranin commented
Foi movida as Strings para o arquivo resource.

obs: Referente ao NavHost foi solicitado a remoção para a developer.

Valeu pelo feedback pessoal.

2024-04-15 19:55 UTC, N0stalgiaUltra approved these changes

2024-05-05 00:17 UTC, merged