Documentação tela de data de nascimento e tela raça e porte.
PetJournal/petjournal.android pull request #61
Opened 2024-05-18 18:52 UTC by JorgeTranin

- Criação diagrama tela data de nascimento e tela raça e porte.
- Atualização do Readme.

2024-05-18 21:23 UTC, gusoliveira21 requested changes

2024-05-18 21:23 UTC, gusoliveira21 commented on doc/screens/tela_padrao_data_de_nascimento.md
> +      ![Tela_padrão_Data_de_Nascimento](https://github.com/PetJournal/petjournal.android/assets/63371272/11d0a224-dff9-4a35-b0eb-6453697f2a41)
Tente reestruturar para passar o erro de volta para o condicional "hasMsgErro( )" e não para o representativo do botão "continue".

![VALIDA](https://github.com/PetJournal/petjournal.android/assets/42920754/3e979412-866f-416c-b091-bcd5f21b4953)

2024-05-18 21:23 UTC, gusoliveira21 commented on doc/screens/tela_padrao_raca_e_porte.md
> +      ![Tela_padrão_Raca_e_Porte](https://github.com/PetJournal/petjournal.android/assets/63371272/dfa58cbf-f82d-4b5c-b8a0-7b0a735c9d12)
A) O diagrama mostra que inicialmente é realizado um get ara obter o *petInformation*, mas quem é esse cara? tente descrever quem é esse sujeito para ficar claro. Pode ser no diagrama por meio de um pequeno bloco de texto em formato json com esse objeto ou uma representação dele, ou descrito em texto na propria tela do readme.

Fora que deixa entender que as listas de Size e raça estão dentro da Interface, não no viewModel ou sendo obtidas da api (como é o ideal) por meio das rotas a baixo para cão e gato:

GET
[/sizes/cat](https://petjournal-api-z9gs.onrender.com/api/docs/dark/#/size/get_sizes_cat)
Load cat sizes

GET
[/sizes/dog](https://petjournal-api-z9gs.onrender.com/api/docs/dark/#/size/get_sizes_dog)
Load dog sizes

B) é o mesmo do ponto anterior. O resultado volta direto para o método condicional para verificar se houve um erro ou não, e não passa novamente pelo 'continue'.

![VALIDA2](https://github.com/PetJournal/petjournal.android/assets/42920754/7c0fd2f0-d4a0-462e-b6b6-10324b42be36)

2024-05-21 13:43 UTC, JorgeTranin commented on doc/screens/tela_padrao_raca_e_porte.md
> +      ![Tela_padrão_Raca_e_Porte](https://github.com/PetJournal/petjournal.android/assets/63371272/dfa58cbf-f82d-4b5c-b8a0-7b0a735c9d12)
Foi alterado e atualizado conforme as solicitações e recomendações da equipe.

2024-05-28 15:50 UTC, JorgeTranin commented on doc/screens/tela_padrao_data_de_nascimento.md
> +      ![Tela_padrão_Data_de_Nascimento](https://github.com/PetJournal/petjournal.android/assets/63371272/11d0a224-dff9-4a35-b0eb-6453697f2a41)
Foram feitas melhorias e resolução para o exemplo proposto.

2024-06-02 02:20 UTC, gusoliveira21 approved these changes

2024-06-02 02:21 UTC, merged