Requisição das listas de raça e porte
PetJournal/petjournal.android pull request #64
Opened 2024-06-04 20:31 UTC by JorgeTranin

### Adiciona a funcionalidade de request para lista de raça e porte de pets, para preenchimento dos dropdowns na tela Raça e Porte.

- Adiciona chamadas a api para buscar as listas.
- Salva no banco local.
- Adiciona testes unitários nas camadas de UI, UseCase e DB.
- Retira as listas Mocadas na VM.

2024-06-05 00:16 UTC, gusoliveira21 approved these changes
Wonderfull Code

2024-06-05 00:26 UTC, gusoliveira21 requested changes

2024-06-05 00:26 UTC, gusoliveira21 commented on petJournal/app/src/main/java/com/soujunior/petjournal/ui/screens_app/screens_pets/petRaceAndSizeScreen/ViewModelRaceSizeImpl.kt
> +        viewModelScope.launch {
Consegue me explicar o motivo deste launch esta aqui?

2024-06-18 03:06 UTC, gusoliveira21 requested changes

2024-06-18 03:06 UTC, gusoliveira21 commented on petJournal/database/src/main/java/com/petjournal/database/database/entity/ListPetSizes.kt
> +data class ListPetSizes(
Modificar entidade para receber os itens corretamente. Objeto por objeto e não a string retornada de uma vez.

2024-06-19 20:29 UTC, JorgeTranin commented on petJournal/database/src/main/java/com/petjournal/database/database/entity/ListPetSizes.kt
> +data class ListPetSizes(
Foi modificado conforme solicitado. Agora salva uma lista separada.

2024-06-20 14:06 UTC, N0stalgiaUltra approved these changes

2024-06-20 21:16 UTC, gusoliveira21 approved these changes

2024-06-20 21:19 UTC, merged