add registration and login methods and layouts
PetJournal/petjournal.android pull request #8
Opened 2023-04-17 23:10 UTC by gusoliveira21

2023-04-18 23:32 UTC, gelsonzeferino approved these changes

2023-04-18 23:51 UTC, gelsonzeferino submitted a review, later dismissed
Apenas algumas anotações para corrigirmos ou alterar.

2023-04-18 23:51 UTC, gelsonzeferino commented on petJournal/app/src/main/java/com/soujunior/petjournal/ui/loginScreen/LoginScreen.kt
> +                text = "Loguin",
Corrigir erro de digitação. Linha 220

2023-04-18 23:51 UTC, gelsonzeferino commented on petJournal/app/src/main/java/com/soujunior/petjournal/ui/loginScreen/LoginScreen.kt
> +        text = "Não tem uma conta? Inscrever-se",
Acredito que o melhor seria Inscreva-se. Linha 84.

2023-04-18 23:51 UTC, gelsonzeferino commented on petJournal/app/src/main/java/com/soujunior/petjournal/ui/registerScreen/RegisterScreenViewModelImpl.kt
> +        this.formError.value = "lançar um erro aqui"
Não entendi a linha 32, seria um TODO para tratar o erro posteriormente?

2023-04-19 23:35 UTC, Lsortudo requested changes

2023-04-19 23:35 UTC, Lsortudo commented on petJournal/domain/src/main/java/com/soujunior/domain/usecase/auth/LoginUseCase.kt
> +    }
Refatorar para evitar boilerplate de código já que é utilizado no UseCase de Login e Register.

2023-04-19 23:35 UTC, Lsortudo commented on petJournal/domain/src/main/java/com/soujunior/domain/usecase/auth/RegisterUseCase.kt
> +        } else throw Error("Houve um erro desconhecido!")
Refatorar para evitar boilerplate de código já que é utilizado no UseCase de Login e Register.

2023-04-19 23:35 UTC, Lsortudo commented on petJournal/app/src/main/java/com/soujunior/petjournal/ui/loginScreen/LoginScreen.kt
> +package com.soujunior.petjournal.ui.loginScreen
Componentizar esse arquivo Compose pra abstrair os elementos que podem ser reutilizáveis.

2023-04-19 23:35 UTC, Lsortudo commented on petJournal/app/src/main/java/com/soujunior/petjournal/ui/registerScreen/RegisterScreen.kt
> +fun HandleRegisterResponse(registerScreenViewModel: RegisterScreenViewModel) {
Finalizar a função para mostrar um Dialog com um resultado.

2023-04-19 23:35 UTC, Lsortudo commented on petJournal/app/src/main/java/com/soujunior/petjournal/ui/loginScreen/LoginScreen.kt
> +fun handleLoginResponse(loginScreenViewModel: LoginScreenViewModel) {
Finalizar a função para mostrar um Dialog com um resultado.

2023-04-21 15:43 UTC, Lsortudo approved these changes

2023-05-02 21:39 UTC, Lsortudo commented on petJournal/app/src/main/java/com/soujunior/petjournal/ui/registerScreen/components/ImageLogo.kt
> +}
Todas as telas tem a Logo de forma centralizada, será que pra economizar linhas de código e deixar 'melhor' não poderia criar já o Box ou Column aqui dentro ao invés de quando chama a Logo em suas respectivas telas?

2023-05-02 21:41 UTC, Lsortudo approved these changes

2023-05-02 21:45 UTC, gusoliveira21 commented on petJournal/app/src/main/java/com/soujunior/petjournal/ui/registerScreen/components/ImageLogo.kt
> +}
devido a gente ter criado outra branch a partir dessa, realizar mudanças agora pode prejudicar quando agente for unir elas novamente, mas essa ideia pode ser testada nas telas que estão sendo criadas agora. Se funcionar, a gente refatora depois.

2023-05-03 01:19 UTC, Lsortudo approved these changes

2023-05-03 01:22 UTC, merged